#%RAML 1.0 Trait

queryParameters:
  firstName:
    description: User first name
    required: false
    type: string
    example: 'Bob'
  lastName:
    description: User last name
    required: false
    type: string
    example: 'Frederick'  
  title:  
      description: job title
      required: false
      type: string
      example: 'Manager' 
  DOB:  
      description: Date Of Birth
      required: false
      type: string
      example: "06/21/1980" 
